---
title: "dplyr_examples"
vignette: >
  %\VignetteIndexEntry{dplyr_examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Resources
https://www.neonscience.org/resources/learning-hub/tutorials/grepl-filter-piping-dplyr-r

```{r setup}
library(brentlabRnaSeqTools)
```

filter using grepl
```{r, eval=FALSE}
data <- filter(myData,
            grepl('Peromyscus', scientificName),
            sex == 'F')

View(env_pert_set %>% filter(grepl("6.0|4.0",AUTOSTATUSDECOMP, perl=TRUE))%>%
          select(FASTQFILENAME,
                 FASTQFILENUMBER,
                 AUTOSTATUSDECOMP,
                 MANUALAUDIT,
                 TOTAL_DEDUPLICATED_PERCENTAGE,
                 PROTEIN_CODING_TOTAL,
                 LIBRARYDATE,
                 NAT_COVERAGE,
                 NAT_LOG2CPM,
                 G418_COVERAGE,
                 G418_LOG2CPM,
                 NOT_ALIGNED_TOTAL_PERCENT,
                 NO_FEATURE_PERCENT,
                 INTERGENIC_COVERAGE,
                 LIBRARY_SIZE,
                 EFFECTIVE_UNIQUE_ALIGNMENT))
```

