---
title: "sva"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sva}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(brentlabRnaSeqTools)
# library(sva)
```

[from the kundajelab rnaseq pipeline](https://github.com/kundajelab/autism_rnaseq/blob/main/post_processing/diff_genes_deseq.R)
```{r}
# NOTE: THIS HAS ALREADY BEEN PUT INTO A FUNCTION IN R/surrogate_variables.R

#remove genes with 0 counts 
data=data[rowSums(data)>0,] # don't do this
#DESIGN MATRIX
mod0=model.matrix(~1,data=batches) # make intercept only model
mod1=model.matrix(~Condition+Cell,data=batches) # model with known covariates

#RUN SVA 
sva.obj=svaseq(as.matrix(data),mod1,mod0) # run sva
sur_var=data.frame(sva.obj$sv) # extract SVs
batches=cbind(batches,sur_var) # bind to metadata


#Create DESeq object
dds <- DESeqDataSetFromMatrix(countData = round(data),
                              colData = batches,
                              design = ~Group+X1+X2+X3+X4+X5+X6+X7+X8+X9)
```

